"""add done to card and nullable owner_id

Revision ID: 9786d5759afb
Revises: c0954ea3baf9
Create Date: 2026-03-15 12:47:36.108772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9786d5759afb'
down_revision: Union[str, Sequence[str], None] = 'c0954ea3baf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('cards', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'done')
    op.alter_column('boards', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
